"use client";

import { useEffect, useMemo, useRef } from "react";
import "./scroll-fixes.css";
import "./modern-bank-overrides.css";
import {
  AlertTriangle, ArrowUpRight, Check, CheckCircle2, ChevronDown, CircleDollarSign,
  ClipboardCheck, Clock3, CreditCard, Edit3, Headphones, MoreHorizontal, Paperclip,
  RotateCcw, Send, ShieldCheck, Sparkles, WalletCards, X, Zap,
} from "lucide-react";

import { saveflowMock } from "@/lib/saveflow-mock";

import { apiConfig } from "@/lib/api/config";
import { stageCopy } from "@/lib/flow-machine";
import { useSaveflow, type Message } from "@/lib/use-saveflow";
import type { Analysis } from "@/lib/api/contracts";

export default function Home() {
  const { stage, messages, input, setInput, monthlySaving, setMonthlySaving, saveRate, setSaveRate, consent, setConsent, validation, operationId, failure, startDemo, chooseBankingOption, confirmPlan, checkResult, editPlan, savePlan, cancelPlan, restart, retryAnalysis, canStart, canReset, modelMode, changeModelMode, accessCode, setAccessCode, category, targetAmountFen, usage } = useSaveflow();
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const progress = useMemo(() => stage === "success" ? 100 : stage === "welcome" ? 0 : stage === "analyzing" ? 28 : ["executing", "unknown", "checking"].includes(stage) ? 78 : 54, [stage]);
  useEffect(() => { messagesEndRef.current?.scrollIntoView({ behavior: "smooth", block: "end" }); }, [messages, stage]);
  return <main className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark"><Sparkles size={17} /></div><span>SaveFlow</span></div><div className="workspace-label">个人财务空间</div><nav className="nav-list"><button className="nav-item active"><Headphones size={17} /> 智能助理 <span className="nav-dot" /></button><button className="nav-item"><WalletCards size={17} /> 账户概览</button><button className="nav-item"><CreditCard size={17} /> 卡片管理</button><button className="nav-item"><CircleDollarSign size={17} /> 财务目标</button></nav><div className="sidebar-bottom"><div className="security-note"><ShieldCheck size={16} /><span>演示环境<br /><b>{modelMode === "qwen" ? "Qwen 建议 · 模拟资金操作" : "合成数据 · 无真实扣款"}</b></span></div><button className="profile"><span className="avatar">L</span><span><b>林先生</b><small>演示用户</small></span><MoreHorizontal size={17} /></button></div></aside>
    <section className="chat-area"><header className="chat-header"><div className="agent-title"><div className="agent-avatar"><Sparkles size={16} /></div><div><b>SaveFlow Agent</b><span><i className="online" /> {modelMode === "qwen" ? "Qwen · 自然语言助手" : modelMode === "banking" ? "Banking Agent · 账单与转账预览" : "本地模拟模式"}</span></div></div><div className="header-actions"><span className="stage-pill"><span className="stage-dot" /> {stageCopy[stage]}</span><button className="icon-button" title="重新开始演示" disabled={!canReset} onClick={restart}><RotateCcw size={17} /></button><button className="icon-button" title="更多"><MoreHorizontal size={19} /></button></div></header>
      <div className="flow-strip"><div className="flow-label"><Zap size={14} /> 演示流程</div><div className="flow-track"><span className={progress >= 28 ? "done" : ""}>分析消费</span><ChevronDown size={13} /><span className={progress >= 54 ? "done" : ""}>生成计划</span><ChevronDown size={13} /><span className={progress >= 78 ? "done" : ""}>确认执行</span><ChevronDown size={13} /><span className={progress === 100 ? "done" : ""}>结果反馈</span></div><div className="progress-line"><span style={{ width: `${progress}%` }} /></div></div>
      <div className="messages"><div className="date-divider"><span>今天 09:41</span></div>{messages.map((message) => <MessageBubble key={message.id} message={message} onChoice={chooseBankingOption} />)}{stage === "analyzing" && <div className="typing"><span /><span /><span /> {modelMode === "qwen" ? "Qwen 正在理解你的请求" : modelMode === "banking" ? "Banking Agent 正在处理你的请求" : "Agent 正在整理你的账单"}</div>}{stage === "plan" || stage === "edit" ? <PlanCard category={category} targetAmountFen={targetAmountFen} monthlySaving={monthlySaving} saveRate={saveRate} setMonthlySaving={setMonthlySaving} setSaveRate={setSaveRate} editing={stage === "edit"} onConfirm={confirmPlan} onEdit={editPlan} onCancel={cancelPlan} onSave={savePlan} /> : null}{stage === "error" && <div className="error-actions">{failure === "analysis" ? <button className="primary-button" onClick={retryAnalysis}>重试本次请求</button> : <button className="secondary-button" onClick={editPlan}><Edit3 size={15} /> 修改并重新确认</button>}</div>}{(stage === "unknown" || stage === "checking") && <div className="error-actions" role="status"><p>结果待核实，请勿重复提交。操作编号：{operationId}</p><button className="primary-button" disabled={stage === "checking"} onClick={checkResult}>{stage === "checking" ? "查询中…" : "查询操作结果"}</button></div>}{stage === "executing" && <p role="status">正在提交已确认的计划…</p>}{validation && <p className="validation-message" role="alert">{validation}</p>}{(stage === "success" || stage === "cancelled") && <div className="restart-row"><button className="secondary-button" onClick={restart}><RotateCcw size={15} /> 重新开始演示</button></div>}<div ref={messagesEndRef} /></div>
      <div className="composer-wrap"><div className="model-controls"><label>回复来源 <select aria-label="回复来源" value={modelMode} disabled={!canReset || stage === "analyzing"} onChange={event => changeModelMode(event.target.value as "qwen" | "mock" | "banking")}><option value="banking">Banking Agent</option><option value="qwen">Qwen 储蓄助手</option><option value="mock">离线模拟</option></select></label>{(modelMode === "qwen" || modelMode === "banking" || apiConfig.mode === "http") && <input type="password" aria-label="演示访问码" autoComplete="off" maxLength={128} placeholder="演示访问码（不是 API Key）" value={accessCode} disabled={stage === "analyzing"} onChange={event => setAccessCode(event.target.value)} />}</div><label className="consent-control"><input type="checkbox" checked={consent} disabled={!canStart} onChange={event => setConsent(event.target.checked)} /> {modelMode === "qwen" ? "我同意将输入、最近对话和模拟账单摘要发送至阿里云 Qwen，用于生成建议" : modelMode === "banking" ? "我同意将本次消息发送至阿里云 Qwen 理解请求，并使用模拟数据查询账单或生成转账预览" : "我同意分析本次模拟账单，用于生成储蓄建议"}</label><div className="suggestions">{modelMode === "banking" ? <><button disabled={!canStart || !consent} onClick={() => startDemo("给张三转 500 元")}>给张三转 500 元</button><button disabled={!canStart || !consent} onClick={() => startDemo("给王先生转 500 元")}>给王先生转 500 元</button><button disabled={!canStart || !consent} onClick={() => startDemo("查账单")}>查账单</button></> : <><button disabled={!canStart || !consent} onClick={() => startDemo("我想在年底存下 2 万元")}>年底存下 2 万元</button><button disabled={!canStart || !consent} onClick={() => startDemo("帮我减少娱乐消费")}>减少娱乐消费</button><button disabled={!canStart || !consent} onClick={() => startDemo("找出闲置订阅")}>找出闲置订阅</button></>}</div><div className="composer"><button className="attach"><Paperclip size={18} /></button><input value={input} onChange={(event) => setInput(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.nativeEvent.isComposing && canStart) startDemo(); }} placeholder={modelMode === "banking" ? "输入转账或账单请求…" : "输入你的财务目标..."} maxLength={500} disabled={!canStart} /><button className="send" onClick={() => startDemo()} disabled={!canStart || !consent || !input.trim()}><Send size={17} /></button></div><p>{modelMode === "banking" ? "Banking Agent 只生成正式预览，不会确认或执行转账。" : "当前账单及资金操作为模拟；请勿输入真实账户或身份信息"}</p></div></section>
    <aside className="insights"><div className="insights-heading"><div><span className="eyebrow">LIVE OVERVIEW</span><h2>本次演示</h2></div><button className="icon-button"><MoreHorizontal size={18} /></button></div><div className="goal-card"><div className="card-top"><span>财务目标</span><span className="green-tag">进行中</span></div><strong>{targetAmountFen === null ? "未设置目标" : `¥${(targetAmountFen / 100).toLocaleString()}`}</strong><div className="goal-progress"><span style={{ width: `${targetAmountFen ? Math.min(100, saveflowMock.goal.currentAmount * 100 / targetAmountFen * 100) : 0}%` }} /></div><div className="goal-foot"><span>已完成 ¥{saveflowMock.goal.currentAmount.toLocaleString()}</span><b>合成数据 · {saveflowMock.asOf.slice(0, 10)}</b></div></div><div className="metric-grid"><div className="metric-card"><span>月收入</span><strong>¥{saveflowMock.monthlyIncome.toLocaleString()}</strong><small><ArrowUpRight size={13} /> 稳定</small></div><div className="metric-card"><span>建议储蓄</span><strong>¥{monthlySaving.toLocaleString()}</strong><small><Zap size={13} /> {saveRate}% 比例</small></div></div><div className="activity-card"><div className="section-title"><span>规则预览</span><button>查看全部</button></div><RuleRow icon="餐" label={category} value={`${saveRate}% 储蓄规则`} color="blue" /><RuleRow icon="订" label="订阅服务" value="2 项待确认" color="purple" /></div><div className="tip-card"><div className="tip-icon"><Sparkles size={16} /></div><div><b>{modelMode === "qwen" ? "Qwen 使用情况" : "本次演示提示"}</b><p>{usage && modelMode === "qwen" ? `最近一次：输入 ${usage.inputTokens} / 输出 ${usage.outputTokens} Token。金额以百炼账单为准。` : "先描述目标，确认草稿后仅执行模拟操作。"}</p></div></div></aside>
  </main>;
}

function MessageBubble({ message, onChoice }: { message: Message; onChoice: (optionId: string, label: string) => void }) { return <div className={`message-row ${message.role === "user" ? "user-row" : ""}`}><div className={`message-avatar ${message.role === "user" ? "user-avatar" : ""}`}>{message.role === "user" ? "L" : <Sparkles size={14} />}</div><div className={`bubble ${message.kind || ""}`}><div className="bubble-meta">{message.role === "user" ? "你" : "SaveFlow Agent"}<span>09:4{message.id % 10}</span></div><p>{message.text}</p>{message.kind === "analysis" && <AnalysisCard analysis={message.analysis} />}{message.kind === "result" && <ResultCard />}{message.kind === "banking_clarification" && <BankingClarificationCard data={message.banking} onChoice={onChoice} />}{message.kind === "banking_bill" && <BankingBillCard data={message.banking} />}{message.kind === "banking_preview" && <BankingPreviewCard data={message.banking} />}{message.kind === "error" && <div className="error-banner"><AlertTriangle size={15} /> 结果待核实时请先查询，勿重复提交</div>}</div></div>; }
function BankingClarificationCard({ data, onChoice }: { data?: import("@/lib/banking-agent-client").BankingAgentData; onChoice: (optionId: string, label: string) => void }) { return <div className="banking-choice-card"><b>{data?.question || "请补充信息"}</b><div className="banking-choice-list">{(data?.choices || []).map(choice => <button key={choice.optionId} onClick={() => onChoice(choice.optionId, choice.label)}>{choice.label}</button>)}</div><small>选择仅用于补全本次请求，不代表确认转账。</small></div>; }
function BankingBillCard({ data }: { data?: import("@/lib/banking-agent-client").BankingAgentData }) { const summary = data?.data || {}; return <div className="banking-result-card"><b>{String(summary.month || "")} 账单汇总</b><span>交易 {String(summary.transactionCount ?? 0)} 笔</span><span>收入 ¥{(Number(summary.totalIncomeFen || 0) / 100).toFixed(2)}</span><span>支出 ¥{(Number(summary.totalExpenseFen || 0) / 100).toFixed(2)}</span><small>数据来源：{String(data?.evidence?.[0]?.source || "未知")} · 截至 {String(data?.evidence?.[0]?.asOf || "未知")}</small></div>; }
function BankingPreviewCard({ data }: { data?: import("@/lib/banking-agent-client").BankingAgentData }) { const effect = (data?.preview?.exactEffects as Array<Record<string, unknown>> | undefined)?.[0] || {}; return <div className="banking-preview-card"><div><b>正式转账预览</b><span>等待用户核对</span></div><strong>¥{(Number(effect.amountFen || 0) / 100).toFixed(2)}</strong><p>{String(data?.preview?.summary || "")}</p><p>{String(effect.accountName || effect.fromAccountId || "付款账户")} → {String(effect.payeeName || effect.payeeId || "收款人")}</p><small>预览有效期 {String(data?.preview?.expiresAt || "未知")} · 风险等级 {String(data?.risk?.riskLevel || effect.riskLevel || "未知")} · 操作编号 {data?.operationId}</small></div>; }
function AnalysisCard({ analysis }: { analysis?: Analysis }) { return <div className="analysis-card"><div className="analysis-title"><div className="mini-icon blue"><ClipboardCheck size={15} /></div><div><b>账单分析完成</b><span>合成数据{analysis?.asOf ? ` · 截至 ${analysis.asOf.slice(0, 10)}` : ""}</span></div><CheckCircle2 className="check" size={17} /></div><div className="analysis-stats"><div><span>{analysis?.currentMonth ?? "样例月份"} 支出</span><b>¥{((analysis?.totalExpenseFen ?? 0) / 100).toLocaleString()}</b></div><div><span>环比变化</span><b className="accent">{analysis?.momIncreaseFen === undefined ? "—" : `¥${(analysis.momIncreaseFen / 100).toLocaleString()}`}</b></div><div><span>订阅服务</span><b>{analysis?.subscriptionCount ?? 0} 项</b></div></div>{analysis?.categories?.length ? <div className="analysis-categories">{analysis.categories.map((item) => <span key={item.name}>{item.name} <b>+¥{(item.changeAmountFen / 100).toLocaleString()}</b></span>)}</div> : null}<div className="insight-line"><Sparkles size={14} /> 可调整财务规则，提交前请确认。</div></div>; }
function ResultCard() { return <div className="result-card"><div className="result-check"><Check size={18} /></div><div><b>执行成功</b><span>模拟规则已启用，未发起真实扣款</span></div><div className="result-date"><Clock3 size={13} /> 刚刚</div></div>; }
function PlanCard({ category, targetAmountFen, monthlySaving, saveRate, setMonthlySaving, setSaveRate, editing, onConfirm, onEdit, onCancel, onSave }: { category: string; targetAmountFen: number | null; monthlySaving: number; saveRate: number; setMonthlySaving: (value: number) => void; setSaveRate: (value: number) => void; editing: boolean; onConfirm: () => void; onEdit: () => void; onCancel: () => void; onSave: () => void }) {
  return <div className={`plan-card ${editing ? "editing" : ""}`}><div className="plan-heading"><div className="mini-icon blue"><WalletCards size={16} /></div><div><b>{editing ? "调整财务目标" : "为你生成财务目标"}</b><span>{editing ? "修改后请再次确认金额与比例" : "请核对目标、类别、金额和比例"}</span></div><span className="ai-badge"><Sparkles size={12} /> AI 规划</span></div><div className="plan-main"><div className="plan-number"><span>每月建议储蓄</span>{editing ? <div className="number-input"><span>¥</span><input type="number" min={0.01} max={3000} step={0.01} value={monthlySaving} onChange={(e) => setMonthlySaving(Number(e.target.value))} /></div> : <strong>¥{monthlySaving.toLocaleString()}</strong>}<small>{targetAmountFen && monthlySaving > 0 ? `按模拟余额估算约 ${Math.ceil(Math.max(0, targetAmountFen / 100 - saveflowMock.goal.currentAmount) / monthlySaving)} 个月（不计收益）` : "每月金额为模拟计划设置"}</small></div><div className="plan-rule"><div className="rule-row"><span>{category}</span>{editing ? <input className="rate-input" type="number" min={0} max={100} step={0.01} value={saveRate} onChange={(e) => setSaveRate(Number(e.target.value))} /> : <b>{saveRate}%</b>}<span>储蓄规则</span></div><div className="rule-row"><span>月度上限</span><b>¥3,000</b><span>保护现金流</span></div></div></div><div className="plan-note"><ShieldCheck size={14} /> 本次仅创建模拟储蓄规则；后续资金操作须单独确认</div><div className="plan-actions">{editing ? <><button className="secondary-button" onClick={onCancel}><X size={15} /> 取消本次计划</button><button className="primary-button" onClick={onSave}><Check size={15} /> 保存新计划</button></> : <><button className="text-button" onClick={onCancel}>取消</button><button className="secondary-button" onClick={onEdit}><Edit3 size={15} /> 修改</button><button className="primary-button" onClick={onConfirm}><Check size={15} /> 确认创建计划</button></>}</div></div>;
}
function RuleRow({ icon, label, value, color }: { icon: string; label: string; value: string; color: string }) { return <div className="rule-preview-row"><span className={`rule-icon ${color}`}>{icon}</span><b>{label}</b><span>{value}</span><ChevronDown size={14} /></div>; }
